// ================= EXERCICES =================
// Bibliothèque d'exercices de musculation. Les consignes d'exécution et de sécurité
// reprennent les repères techniques standards enseignés en préparation physique
// (alignement articulaire, dos neutre, amplitude contrôlée, respiration à l'effort) —
// à visée générale, ne remplace pas l'avis d'un professionnel de santé ou d'un coach
// pour un problème physique particulier.
const MUSCLES = [
  { id:"pect", n:"Pectoraux" }, { id:"dos", n:"Dos" }, { id:"epaules", n:"Épaules" },
  { id:"biceps", n:"Biceps" }, { id:"triceps", n:"Triceps" }, { id:"avantbras", n:"Avant-bras" },
  { id:"quadriceps", n:"Quadriceps" }, { id:"ischios", n:"Ischio-jambiers" }, { id:"fessiers", n:"Fessiers" },
  { id:"mollets", n:"Mollets" }, { id:"abdos", n:"Abdominaux" }, { id:"cardio", n:"Cardio / gainage dynamique" },
];
const MUSCLE_MAP = {}; MUSCLES.forEach(m=>MUSCLE_MAP[m.id]=m);

// [id, nom, [muscles: primaire d'abord], [équipement requis], pattern, unilatéral,
//  {sets,repsMin,repsMax,restSec}, [consignes], sécurité]
const EXO_RAW = [
["pompes","Pompes",["pect","triceps","epaules"],["bodyweight"],"push",false,{sets:3,repsMin:8,repsMax:15,restSec:75},
  ["Mains sous les épaules, corps aligné tête-bassin-talons.","Descends en gardant les coudes à ~45° du corps, poitrine proche du sol.","Pousse en expirant sans casser l'alignement du bassin."],
  "Si le bas du dos s'affaisse, pose les genoux au sol (variante régressive) plutôt que de forcer la forme."],
["pompes_genoux","Pompes sur les genoux",["pect","triceps","epaules"],["bodyweight"],"push",false,{sets:3,repsMin:10,repsMax:15,restSec:60},
  ["Genoux au sol, corps aligné épaules-genoux.","Descends poitrine proche du sol, coudes à ~45°.","Pousse en expirant."],
  "Bonne alternative pour progresser vers la pompe classique sans compenser avec le bas du dos."],
["pompes_surelevees","Pompes surélevées (mains sur banc)",["pect","triceps","epaules"],["bodyweight","bench"],"push",false,{sets:3,repsMin:10,repsMax:15,restSec:60},
  ["Mains posées sur le banc, corps aligné.","Descends la poitrine vers le banc, coudes semi-serrés.","Pousse en expirant."],
  "Version plus facile que la pompe au sol : utile en régression."],
["pompes_declinees","Pompes déclinées (pieds sur banc)",["pect","epaules","triceps"],["bodyweight","bench"],"push",false,{sets:3,repsMin:6,repsMax:12,restSec:75},
  ["Pieds sur le banc, mains au sol sous les épaules.","Descends poitrine vers le sol en gardant le gainage.","Pousse en expirant."],
  "Plus exigeant pour les épaules : progresse depuis la pompe classique avant cette variante."],
["dips_banc","Dips sur banc",["triceps","epaules","pect"],["bodyweight","bench"],"push",false,{sets:3,repsMin:8,repsMax:15,restSec:60},
  ["Mains sur le bord du banc, jambes tendues ou fléchies, bassin près du banc.","Descends en fléchissant les coudes vers l'arrière, sans dépasser 90°.","Remonte en poussant sur les paumes."],
  "Ne descends pas au-delà d'un angle de coude confortable : une flexion excessive stresse l'épaule."],
["squat_pdc","Squat au poids du corps",["quadriceps","fessiers"],["bodyweight"],"squat",false,{sets:3,repsMin:12,repsMax:20,restSec:60},
  ["Pieds largeur d'épaules, orteils légèrement ouverts.","Descends hanches en arrière et vers le bas, dos neutre, genoux dans l'axe des pieds.","Remonte en poussant le sol en expirant."],
  "Arrête la descente si les talons décollent ou si le bas du dos s'arrondit fortement."],
["squat_bulgare_pdc","Squat bulgare (pied arrière surélevé)",["quadriceps","fessiers"],["bodyweight","bench"],"lunge",true,{sets:3,repsMin:8,repsMax:12,restSec:75},
  ["Pied arrière posé sur le banc, pied avant à bonne distance pour un genou avant proche de 90°.","Descends à la verticale, genou avant aligné avec le pied.","Remonte en poussant sur le talon avant."],
  "Reste proche d'un support au début : exercice exigeant en équilibre."],
["fentes_avant","Fentes avant",["quadriceps","fessiers"],["bodyweight"],"lunge",true,{sets:3,repsMin:10,repsMax:14,restSec:60},
  ["Grand pas en avant, descends jusqu'à ce que les deux genoux soient proches de 90°.","Genou avant aligné avec le pied, buste droit.","Repousse sur le talon avant pour revenir."],
  "Le genou avant ne doit pas dépasser largement la pointe du pied de façon instable."],
["fentes_arriere","Fentes arrière",["quadriceps","fessiers"],["bodyweight"],"lunge",true,{sets:3,repsMin:10,repsMax:14,restSec:60},
  ["Grand pas en arrière, descends le genou arrière vers le sol sans le poser durement.","Buste droit, poids sur la jambe avant.","Repousse sur le talon avant."],
  "Variante souvent plus confortable pour les genoux sensibles que la fente avant."],
["fentes_marchees","Fentes marchées",["quadriceps","fessiers"],["bodyweight"],"lunge",true,{sets:3,repsMin:10,repsMax:16,restSec:75},
  ["Avance en fente, genou avant à ~90°, puis enchaîne le pas suivant.","Garde le buste droit et le gainage actif.","Alterne les jambes à chaque pas."],
  "Prévoir assez d'espace ; ralentis si l'équilibre devient précaire."],
["pont_fessier","Pont fessier",["fessiers","ischios"],["bodyweight"],"hinge",false,{sets:3,repsMin:12,repsMax:20,restSec:45},
  ["Allongé, genoux fléchis, pieds à plat proches du bassin.","Pousse les hanches vers le haut en serrant les fessiers, corps aligné genoux-hanches-épaules.","Redescends contrôlé sans reposer complètement."],
  "Évite de cambrer excessivement le bas du dos en haut du mouvement."],
["pont_fessier_uni","Pont fessier unilatéral",["fessiers","ischios"],["bodyweight"],"hinge",true,{sets:3,repsMin:8,repsMax:12,restSec:45},
  ["Une jambe tendue en l'air, l'autre pied au sol.","Pousse les hanches vers le haut en gardant le bassin de niveau.","Redescends contrôlé."],
  "Si le bassin bascule d'un côté, réduis l'amplitude."],
["planche","Planche (gainage)",["abdos"],["bodyweight"],"core",false,{sets:3,repsMin:20,repsMax:45,restSec:45},
  ["Avant-bras au sol sous les épaules, corps aligné tête-talons.","Serre abdos et fessiers, ne laisse pas le bassin tomber ni monter.","Respire normalement pendant le maintien (durée en secondes)."],
  "Arrête si le bas du dos se creuse : réduis la durée plutôt que de perdre la position."],
["planche_laterale","Planche latérale",["abdos"],["bodyweight"],"core",true,{sets:3,repsMin:15,repsMax:30,restSec:45},
  ["Appui sur un avant-bras, corps aligné de la tête aux pieds.","Hanche décollée du sol, gainage latéral actif.","Maintiens la position (durée en secondes) puis change de côté."],
  "Empile bien les épaules et les hanches pour ne pas tourner le buste."],
["superman","Superman",["dos","fessiers"],["bodyweight"],"core",false,{sets:3,repsMin:10,repsMax:15,restSec:45},
  ["Allongé sur le ventre, bras tendus devant.","Soulève simultanément bras, poitrine et jambes de quelques centimètres.","Redescends contrôlé."],
  "Mouvement d'amplitude modérée : ne cherche pas à monter très haut, privilégie le contrôle."],
["mountain_climbers","Mountain climbers",["abdos","cardio"],["bodyweight"],"core",false,{sets:3,repsMin:20,repsMax:30,restSec:45},
  ["Position de planche haute, mains sous les épaules.","Ramène un genou vers la poitrine puis alterne rapidement.","Garde le bassin stable, sans le faire remonter."],
  "Ralentis si le bas du dos bouge beaucoup : la stabilité du bassin prime sur la vitesse."],
["crunch","Crunch abdominaux",["abdos"],["bodyweight"],"core",false,{sets:3,repsMin:15,repsMax:25,restSec:45},
  ["Allongé, genoux fléchis, mains légèrement derrière la tête sans tirer sur la nuque.","Enroule le buste vers les genoux en expirant.","Redescends contrôlé sans reposer brutalement."],
  "Ne tire pas sur la tête avec les mains ; le mouvement vient des abdominaux."],
["releve_jambes","Relevé de jambes",["abdos"],["bodyweight"],"core",false,{sets:3,repsMin:10,repsMax:15,restSec:45},
  ["Allongé, jambes tendues, bas du dos au contact du sol.","Descends les jambes tant que le bas du dos reste plaqué au sol.","Remonte contrôlé."],
  "Plie les genoux pour réduire le levier si le bas du dos décolle du sol."],
["burpees","Burpees",["cardio","quadriceps","pect"],["bodyweight"],"core",false,{sets:3,repsMin:8,repsMax:15,restSec:60},
  ["Depuis debout, descends en squat, pose les mains, envoie les pieds en planche.","Fais une pompe (optionnelle), ramène les pieds, saute vers le haut.","Enchaîne à un rythme régulier plutôt que maximal d'emblée."],
  "Exercice cardiovasculaire exigeant : ralentis la cadence en cas d'essoufflement excessif."],
["jumping_jacks","Jumping jacks",["cardio"],["bodyweight"],"core",false,{sets:3,repsMin:20,repsMax:40,restSec:30},
  ["Départ pieds joints, bras le long du corps.","Saute en écartant simultanément jambes et bras au-dessus de la tête.","Reviens à la position de départ, enchaîne à rythme régulier."],
  "Bon échauffement cardio ; réduis l'amplitude si les articulations des chevilles/genoux sont sensibles."],
["bird_dog","Bird-dog",["abdos","dos"],["bodyweight"],"core",true,{sets:3,repsMin:8,repsMax:12,restSec:45},
  ["À quatre pattes, dos neutre.","Tends simultanément un bras et la jambe opposée à l'horizontale.","Reviens contrôlé, alterne les côtés."],
  "Garde le bassin stable : évite de le faire tourner pendant l'extension."],
["mollets_pdc","Mollets debout (poids du corps)",["mollets"],["bodyweight"],"calf",false,{sets:3,repsMin:15,repsMax:25,restSec:45},
  ["Debout, pieds à plat, éventuellement en appui sur un support pour l'équilibre.","Monte sur la pointe des pieds le plus haut possible.","Redescends contrôlé sans rebondir."],
  "Mouvement lent et contrôlé plutôt que rebondi, pour bien solliciter le mollet."],
["chaise_murale","Chaise contre le mur",["quadriceps"],["bodyweight"],"squat",false,{sets:3,repsMin:20,repsMax:45,restSec:45},
  ["Dos au mur, descends jusqu'à cuisses proches de l'horizontale, genoux à 90°.","Maintiens la position (durée en secondes), genoux alignés avec les pieds.","Remonte en poussant sur les talons."],
  "Arrête si une douleur au genou apparaît (différente de la fatigue musculaire normale)."],
["pompe_pike","Pompe pike",["epaules","triceps"],["bodyweight"],"push",false,{sets:3,repsMin:6,repsMax:12,restSec:75},
  ["Position en V inversé, mains au sol, hanches hautes.","Descends la tête vers le sol en fléchissant les coudes.","Repousse pour revenir en position haute."],
  "Bonne préparation au développé militaire sans charge ; progresse graduellement en amplitude."],
["tractions","Tractions (pronation)",["dos","biceps"],["bodyweight","pullup_bar"],"pull",false,{sets:3,repsMin:4,repsMax:10,restSec:90},
  ["Suspendu, mains un peu plus larges que les épaules, paumes vers l'avant.","Tire en amenant le menton au-dessus de la barre, coudes vers le bas.","Redescends contrôlé jusqu'à extension complète des bras."],
  "Évite les à-coups (kipping non contrôlé) qui stressent l'épaule ; privilégie un mouvement strict."],
["tractions_suppination","Tractions (supination)",["biceps","dos"],["bodyweight","pullup_bar"],"pull",false,{sets:3,repsMin:4,repsMax:10,restSec:90},
  ["Suspendu, paumes vers soi, mains largeur d'épaules.","Tire en amenant le menton au-dessus de la barre.","Redescends contrôlé jusqu'à extension complète."],
  "Sollicite davantage les biceps ; même prudence que la traction classique sur les à-coups."],
["suspension_barre","Suspension à la barre",["avantbras","dos"],["bodyweight","pullup_bar"],"pull",false,{sets:3,repsMin:20,repsMax:40,restSec:60},
  ["Suspendu à la barre, épaules légèrement engagées (pas totalement relâchées).","Maintiens la position (durée en secondes).","Redescends en douceur."],
  "Bon exercice de renforcement des avant-bras et de décompression du dos, à intensité douce."],
["dc_haltere","Développé couché haltères",["pect","triceps","epaules"],["dumbbells","bench"],"push",false,{sets:3,repsMin:8,repsMax:12,restSec:90},
  ["Allongé sur le banc, haltères au niveau de la poitrine, coudes à ~45°.","Pousse les haltères vers le haut sans les entrechoquer, extension quasi complète.","Redescends contrôlé jusqu'à un étirement confortable de la poitrine."],
  "Garde toujours le contrôle de la charge, surtout en fin de série ; utilise un poids que tu peux reposer en sécurité."],
["dc_incline_haltere","Développé incliné haltères",["pect","epaules","triceps"],["dumbbells","bench"],"push",false,{sets:3,repsMin:8,repsMax:12,restSec:90},
  ["Banc incliné à 30-45°, haltères au niveau du haut de la poitrine.","Pousse vers le haut en gardant les omoplates serrées contre le banc.","Redescends contrôlé."],
  "Une inclinaison trop forte (>45°) sollicite davantage l'épaule que le haut des pectoraux."],
["ecarte_couche","Écarté couché haltères",["pect"],["dumbbells","bench"],"push",false,{sets:3,repsMin:10,repsMax:15,restSec:75},
  ["Allongé, haltères au-dessus de la poitrine, légère flexion des coudes maintenue.","Ouvre les bras en arc de cercle jusqu'à un étirement confortable.","Ramène les haltères en contractant les pectoraux."],
  "Ne descends pas plus bas que ce que l'épaule tolère sans tension excessive à l'avant."],
["rowing_uni_haltere","Rowing haltère unilatéral",["dos","biceps"],["dumbbells","bench"],"pull",true,{sets:3,repsMin:8,repsMax:12,restSec:75},
  ["Un genou et une main en appui sur le banc, dos plat et parallèle au sol.","Tire l'haltère vers la hanche en amenant le coude vers l'arrière.","Redescends contrôlé jusqu'à extension complète du bras."],
  "Garde le dos plat pendant tout le mouvement, sans le tordre pour tirer la charge."],
["rowing_deux_halteres","Rowing buste penché (deux haltères)",["dos","biceps"],["dumbbells"],"pull",false,{sets:3,repsMin:8,repsMax:12,restSec:75},
  ["Buste penché en avant, dos plat, genoux légèrement fléchis, haltères pendants.","Tire les haltères vers les hanches, coudes vers l'arrière.","Redescends contrôlé."],
  "Garde le dos neutre tout du long ; si tu ne peux pas maintenir cet angle, redresse un peu le buste."],
["dev_epaules_haltere","Développé épaules haltères",["epaules","triceps"],["dumbbells"],"push",false,{sets:3,repsMin:8,repsMax:12,restSec:90},
  ["Assis ou debout, haltères au niveau des épaules, paumes vers l'avant.","Pousse vers le haut sans cambrer excessivement le bas du dos.","Redescends contrôlé jusqu'aux épaules."],
  "Garde le gainage actif pour éviter de compenser avec le bas du dos, surtout debout."],
["elevations_laterales","Élévations latérales",["epaules"],["dumbbells"],"push",false,{sets:3,repsMin:12,repsMax:15,restSec:60},
  ["Debout, haltères le long du corps, légère flexion des coudes.","Lève les bras sur les côtés jusqu'à hauteur d'épaule.","Redescends contrôlé sans élan."],
  "Évite de monter au-dessus de la hauteur d'épaule avec une charge lourde : cela stresse l'articulation."],
["elevations_frontales","Élévations frontales",["epaules"],["dumbbells"],"push",false,{sets:3,repsMin:10,repsMax:15,restSec:60},
  ["Debout, haltères devant les cuisses.","Lève un bras (ou les deux) tendu jusqu'à hauteur d'épaule.","Redescends contrôlé."],
  "Ne cambre pas le dos pour gagner de l'amplitude : garde le buste stable."],
["oiseau_haltere","Oiseau (élévation arrière)",["epaules","dos"],["dumbbells"],"pull",false,{sets:3,repsMin:12,repsMax:15,restSec:60},
  ["Buste penché en avant, dos plat, haltères pendants devant.","Écarte les bras sur les côtés en serrant les omoplates.","Redescends contrôlé."],
  "Utilise une charge légère : c'est un mouvement d'isolation qui tolère peu de triche."],
["curl_biceps","Curl biceps haltères",["biceps"],["dumbbells"],"pull",false,{sets:3,repsMin:8,repsMax:12,restSec:60},
  ["Debout, haltères le long du corps, coudes proches du buste.","Fléchis les coudes pour monter les haltères, sans balancer le buste.","Redescends contrôlé jusqu'à extension complète."],
  "Évite l'élan du buste pour « tricher » la fin de série : réduis la charge plutôt."],
["curl_marteau","Curl marteau",["biceps","avantbras"],["dumbbells"],"pull",false,{sets:3,repsMin:8,repsMax:12,restSec:60},
  ["Debout, haltères en prise neutre (paumes face à face).","Fléchis les coudes en gardant les poignets neutres.","Redescends contrôlé."],
  "Sollicite aussi l'avant-bras ; garde un tempo contrôlé pour éviter les à-coups au poignet."],
["extension_triceps_nuque","Extension triceps nuque",["triceps"],["dumbbells"],"push",false,{sets:3,repsMin:8,repsMax:12,restSec:75},
  ["Assis ou debout, un haltère tenu à deux mains au-dessus de la tête.","Descends l'haltère derrière la tête en fléchissant les coudes, coudes fixes.","Remonte en étendant les bras sans les verrouiller brutalement."],
  "Garde les coudes proches de la tête ; ne descends pas si tu perds le contrôle de la charge."],
["kickback_triceps","Kickback triceps",["triceps"],["dumbbells","bench"],"push",true,{sets:3,repsMin:10,repsMax:15,restSec:60},
  ["Buste penché, un genou et une main en appui sur le banc, bras haut parallèle au sol.","Étends l'avant-bras vers l'arrière, coude fixe.","Reviens contrôlé."],
  "Mouvement d'isolation léger : privilégie la maîtrise du geste à la charge."],
["squat_gobelet","Squat gobelet (goblet squat)",["quadriceps","fessiers"],["dumbbells"],"squat",false,{sets:3,repsMin:10,repsMax:15,restSec:90},
  ["Tiens un haltère à deux mains contre la poitrine.","Descends hanches en arrière et vers le bas, dos neutre, coudes entre les genoux.","Remonte en poussant le sol."],
  "Excellent exercice d'apprentissage du squat : privilégie la profondeur atteignable sans arrondir le dos."],
["fentes_halteres","Fentes haltères",["quadriceps","fessiers"],["dumbbells"],"lunge",true,{sets:3,repsMin:8,repsMax:12,restSec:75},
  ["Haltères le long du corps, grand pas en avant ou en arrière.","Descends jusqu'à un angle proche de 90° au genou avant.","Repousse sur le talon avant pour revenir."],
  "Commence avec une charge légère pour valider l'équilibre avant d'augmenter le poids."],
["rdl_halteres","Soulevé de terre jambes tendues (haltères)",["ischios","fessiers"],["dumbbells"],"hinge",false,{sets:3,repsMin:8,repsMax:12,restSec:90},
  ["Haltères devant les cuisses, genoux légèrement fléchis, dos neutre.","Bascule le bassin en arrière en laissant descendre les haltères le long des jambes.","Remonte en poussant les hanches vers l'avant, sans arrondir le dos."],
  "Le dos doit rester neutre du début à la fin ; arrête la descente dès que tu sens le dos s'arrondir."],
["rdl_uni_haltere","Soulevé de terre roumain unilatéral",["ischios","fessiers"],["dumbbells"],"hinge",true,{sets:3,repsMin:6,repsMax:10,restSec:75},
  ["Sur une jambe, haltère du côté opposé, dos neutre.","Bascule le buste vers l'avant en levant la jambe libre vers l'arrière.","Reviens contrôlé en gardant le bassin de niveau."],
  "Exercice d'équilibre exigeant : commence à charge très légère voire à vide."],
["mollets_halteres","Mollets debout (haltères)",["mollets"],["dumbbells"],"calf",false,{sets:3,repsMin:15,repsMax:20,restSec:45},
  ["Haltères le long du corps, pieds à plat.","Monte sur la pointe des pieds le plus haut possible.","Redescends contrôlé sans rebondir."],
  "Mouvement lent, amplitude complète, sans rebond pour maximiser le travail du mollet."],
["shrugs_halteres","Shrugs (trapèzes) haltères",["dos"],["dumbbells"],"pull",false,{sets:3,repsMin:12,repsMax:15,restSec:60},
  ["Debout, haltères le long du corps.","Monte les épaules vers les oreilles sans rouler les épaules.","Redescends contrôlé."],
  "Évite de rouler les épaules en cercle avec une charge lourde : monte-descends verticalement."],
["thruster_haltere","Thruster haltères",["quadriceps","epaules","fessiers"],["dumbbells"],"squat",false,{sets:3,repsMin:8,repsMax:12,restSec:90},
  ["Haltères au niveau des épaules, descends en squat complet.","Remonte en poussant sur les jambes et enchaîne un développé épaules.","Redescends les haltères aux épaules avant la répétition suivante."],
  "Exercice combiné exigeant en cardio : commence avec une charge modérée pour garder la forme."],
["squat_barre","Squat barre (back squat)",["quadriceps","fessiers"],["barbell"],"squat",false,{sets:4,repsMin:5,repsMax:10,restSec:120},
  ["Barre posée sur le haut du dos (trapèzes), pieds largeur d'épaules.","Descends hanches en arrière et vers le bas, dos neutre, genoux dans l'axe des pieds.","Remonte en poussant le sol, sans perdre l'alignement du dos."],
  "Utilise un cadre de sécurité ou des supports réglés à hauteur de squat si tu t'entraînes seul avec une charge proche du maximum."],
["dc_barre","Développé couché barre",["pect","triceps","epaules"],["barbell","bench"],"push",false,{sets:4,repsMin:5,repsMax:10,restSec:120},
  ["Allongé, prise un peu plus large que les épaules, barre au niveau de la poitrine.","Descends la barre contrôlée jusqu'à toucher légèrement la poitrine.","Pousse vers le haut en expirant, sans rebondir sur la poitrine."],
  "Entraîne-toi avec un partenaire ou des butées de sécurité pour les charges proches du maximum ; ne bloque jamais les coudes brutalement."],
["deadlift_barre","Soulevé de terre (deadlift)",["ischios","fessiers","dos"],["barbell"],"hinge",false,{sets:4,repsMin:4,repsMax:8,restSec:150},
  ["Barre proche des tibias, dos neutre, poitrine haute, prise juste à l'extérieur des jambes.","Pousse le sol avec les jambes en gardant la barre proche du corps jusqu'à l'extension complète des hanches.","Redescends en inversant le mouvement, dos toujours neutre."],
  "Le soulevé de terre est technique : commence avec une charge légère pour ancrer la position de dos neutre avant de charger davantage."],
["militaire_barre","Développé militaire barre",["epaules","triceps"],["barbell"],"push",false,{sets:3,repsMin:6,repsMax:10,restSec:120},
  ["Debout, barre au niveau des clavicules, prise un peu plus large que les épaules.","Pousse la barre au-dessus de la tête en gainant fort, sans cambrer excessivement.","Redescends contrôlé jusqu'aux clavicules."],
  "Garde les abdos et fessiers contractés pour protéger le bas du dos pendant la poussée."],
["rowing_barre","Rowing barre buste penché",["dos","biceps"],["barbell"],"pull",false,{sets:3,repsMin:6,repsMax:10,restSec:90},
  ["Buste penché à ~45°, dos neutre, barre pendante bras tendus.","Tire la barre vers le bas du buste, coudes vers l'arrière.","Redescends contrôlé sans perdre l'angle du dos."],
  "Si tu ne peux pas garder le dos neutre à cet angle, redresse légèrement le buste ou réduis la charge."],
["hip_thrust_barre","Hip thrust barre",["fessiers","ischios"],["barbell","bench"],"hinge",false,{sets:3,repsMin:8,repsMax:12,restSec:90},
  ["Haut du dos calé sur le banc, barre sur les hanches (protège avec une serviette/pad).","Pousse les hanches vers le haut jusqu'à extension complète, menton rentré.","Redescends contrôlé sans reposer brutalement."],
  "Positionne la barre confortablement sur les hanches avant de charger lourd pour éviter l'inconfort."],
["swing_kb","Swing kettlebell",["fessiers","ischios","cardio"],["kettlebell"],"hinge",false,{sets:3,repsMin:12,repsMax:20,restSec:75},
  ["Pieds largeur d'épaules, kettlebell tenue à deux mains devant.","Bascule le bassin en arrière (hinge, pas un squat) puis pousse les hanches vers l'avant pour projeter la kettlebell à hauteur de poitrine.","Laisse la kettlebell redescendre entre les jambes en contrôlant le mouvement."],
  "Le mouvement part des hanches, pas des bras ni du bas du dos : arrête si tu sens le dos travailler plus que les hanches."],
["goblet_squat_kb","Goblet squat kettlebell",["quadriceps","fessiers"],["kettlebell"],"squat",false,{sets:3,repsMin:10,repsMax:15,restSec:90},
  ["Kettlebell tenue contre la poitrine par les cornes.","Descends hanches en arrière et vers le bas, dos neutre.","Remonte en poussant le sol."],
  "Même repère de sécurité que le goblet squat haltère : privilégie la profondeur atteignable sans arrondir le dos."],
["deadlift_kb","Soulevé de terre kettlebell",["ischios","fessiers"],["kettlebell"],"hinge",false,{sets:3,repsMin:8,repsMax:12,restSec:90},
  ["Kettlebell entre les pieds, dos neutre, genoux légèrement fléchis.","Pousse le sol avec les jambes en gardant la kettlebell proche du corps.","Redescends contrôlé, dos toujours neutre."],
  "Charge légère au départ pour ancrer la technique de hinge avant d'augmenter le poids."],
["rowing_uni_kb","Rowing kettlebell unilatéral",["dos","biceps"],["kettlebell","bench"],"pull",true,{sets:3,repsMin:8,repsMax:12,restSec:75},
  ["Un genou et une main en appui sur le banc, dos plat.","Tire la kettlebell vers la hanche, coude vers l'arrière.","Redescends contrôlé."],
  "Garde le dos plat pendant tout le mouvement."],
["kb_overhead_press","Développé kettlebell",["epaules","triceps"],["kettlebell"],"push",true,{sets:3,repsMin:6,repsMax:10,restSec:90},
  ["Kettlebell en position de rack contre l'avant-bras/épaule.","Pousse vers le haut jusqu'à extension complète du bras.","Redescends contrôlé jusqu'au rack."],
  "Garde le gainage actif ; travaille un bras à la fois pour bien contrôler la trajectoire."],
["tirage_elastique","Tirage élastique horizontal",["dos","biceps"],["bands"],"pull",false,{sets:3,repsMin:12,repsMax:20,restSec:60},
  ["Élastique fixé à hauteur de poitrine ou tenu tendu devant soi, bras tendus.","Tire les mains vers les côtes en serrant les omoplates.","Reviens contrôlé jusqu'à extension complète."],
  "Choisis une résistance qui permet de garder le buste immobile pendant toute la série."],
["ecarte_elastique","Écarté élastique (pull-apart)",["epaules","dos"],["bands"],"pull",false,{sets:3,repsMin:12,repsMax:20,restSec:45},
  ["Élastique tenu à deux mains devant soi, bras tendus.","Écarte les mains en ouvrant les bras jusqu'à ce que l'élastique touche la poitrine.","Reviens contrôlé."],
  "Excellent exercice de santé d'épaule ; privilégie un tempo lent et contrôlé."],
["squat_elastique","Squat élastique",["quadriceps","fessiers"],["bands"],"squat",false,{sets:3,repsMin:12,repsMax:20,restSec:60},
  ["Élastique sous les pieds, tenu au niveau des épaules ou fixé sous les pieds selon le modèle.","Descends en squat, dos neutre, genoux dans l'axe des pieds.","Remonte en poussant le sol contre la résistance."],
  "Garde la même vigilance sur l'alignement des genoux que pour un squat classique."],
["extension_triceps_elastique","Extension triceps élastique",["triceps"],["bands"],"push",false,{sets:3,repsMin:12,repsMax:20,restSec:45},
  ["Élastique fixé en hauteur, coude fléchi près de la tête.","Étends l'avant-bras vers le bas, coude fixe.","Reviens contrôlé."],
  "Garde le coude immobile tout du long pour bien isoler le triceps."],
["curl_biceps_elastique","Curl biceps élastique",["biceps"],["bands"],"pull",false,{sets:3,repsMin:12,repsMax:20,restSec:45},
  ["Élastique sous les pieds, coudes proches du buste.","Fléchis les coudes pour amener les mains vers les épaules.","Reviens contrôlé."],
  "Évite de balancer le buste pour compenser en fin de série."],
["band_walk","Marche latérale élastique",["fessiers"],["bands"],"squat",true,{sets:3,repsMin:10,repsMax:15,restSec:45},
  ["Élastique placé au-dessus des genoux ou des chevilles, légère flexion des genoux.","Fais des pas latéraux en gardant la tension dans l'élastique.","Garde les hanches de niveau, sans te pencher."],
  "Reste en position mi-squat basse tout du long pour maximiser le travail des fessiers moyens."],
];

const EXOS = EXO_RAW.map(([id,n,muscles,equip,pattern,uni,def,cues,safety])=>({
  id,n,muscles,equip,pattern,uni,
  sets:def.sets,repsMin:def.repsMin,repsMax:def.repsMax,restSec:def.restSec,
  cues,safety
}));
const EXO_MAP = {}; EXOS.forEach(e=>EXO_MAP[e.id]=e);
