// ================= EXERCICES =================
// Bibliothèque d'exercices de musculation. Les consignes d'exécution et de sécurité
// reprennent les repères techniques standards enseignés en préparation physique
// (alignement articulaire, dos neutre, amplitude contrôlée, respiration à l'effort) —
// à visée générale, ne remplace pas l'avis d'un professionnel de santé ou d'un coach
// pour un problème physique particulier.
const MUSCLES = [
  { id:"pect", n:"Pectoraux" }, { id:"dos", n:"Dos" }, { id:"epaules", n:"Épaules" },
  { id:"biceps", n:"Biceps" }, { id:"triceps", n:"Triceps" }, { id:"avantbras", n:"Avant-bras" },
  { id:"quadriceps", n:"Quadriceps" }, { id:"ischios", n:"Ischio-jambiers" }, { id:"fessiers", n:"Fessiers" },
  { id:"mollets", n:"Mollets" }, { id:"abdos", n:"Abdominaux" }, { id:"cardio", n:"Cardio / gainage dynamique" },
];
const MUSCLE_MAP = {}; MUSCLES.forEach(m=>MUSCLE_MAP[m.id]=m);

// [id, nom, [muscles: primaire d'abord], [équipement requis], pattern, unilatéral,
//  {sets,repsMin,repsMax,restSec}, [consignes], sécurité]
const EXO_RAW = [
["pompes","Pompes",["pect","triceps","epaules"],["bodyweight"],"push",false,{sets:3,repsMin:8,repsMax:15,restSec:75},
  ["Mains sous les épaules, corps aligné tête-bassin-talons.","Descends en gardant les coudes à ~45° du corps, poitrine proche du sol.","Pousse en expirant sans casser l'alignement du bassin."],
  "Si le bas du dos s'affaisse, pose les genoux au sol (variante régressive) plutôt que de forcer la forme."],
["pompes_genoux","Pompes sur les genoux",["pect","triceps","epaules"],["bodyweight"],"push",false,{sets:3,repsMin:10,repsMax:15,restSec:60},
  ["Genoux au sol, corps aligné épaules-genoux.","Descends poitrine proche du sol, coudes à ~45°.","Pousse en expirant."],
  "Bonne alternative pour progresser vers la pompe classique sans compenser avec le bas du dos."],
["pompes_surelevees","Pompes surélevées (mains sur banc)",["pect","triceps","epaules"],["bodyweight","bench"],"push",false,{sets:3,repsMin:10,repsMax:15,restSec:60},
  ["Mains posées sur le banc, corps aligné.","Descends la poitrine vers le banc, coudes semi-serrés.","Pousse en expirant."],
  "Version plus facile que la pompe au sol : utile en régression."],
["pompes_declinees","Pompes déclinées (pieds sur banc)",["pect","epaules","triceps"],["bodyweight","bench"],"push",false,{sets:3,repsMin:6,repsMax:12,restSec:75},
  ["Pieds sur le banc, mains au sol sous les épaules.","Descends poitrine vers le sol en gardant le gainage.","Pousse en expirant."],
  "Plus exigeant pour les épaules : progresse depuis la pompe classique avant cette variante."],
["dips_banc","Dips sur banc",["triceps","epaules","pect"],["bodyweight","bench"],"push",false,{sets:3,repsMin:8,repsMax:15,restSec:60},
  ["Mains sur le bord du banc, jambes tendues ou fléchies, bassin près du banc.","Descends en fléchissant les coudes vers l'arrière, sans dépasser 90°.","Remonte en poussant sur les paumes."],
  "Ne descends pas au-delà d'un angle de coude confortable : une flexion excessive stresse l'épaule."],
["squat_pdc","Squat au poids du corps",["quadriceps","fessiers"],["bodyweight"],"squat",false,{sets:3,repsMin:12,repsMax:20,restSec:60},
  ["Pieds largeur d'épaules, orteils légèrement ouverts.","Descends hanches en arrière et vers le bas, dos neutre, genoux dans l'axe des pieds.","Remonte en poussant le sol en expirant."],
  "Arrête la descente si les talons décollent ou si le bas du dos s'arrondit fortement."],
["squat_bulgare_pdc","Squat bulgare (pied arrière surélevé)",["quadriceps","fessiers"],["bodyweight","bench"],"lunge",true,{sets:3,repsMin:8,repsMax:12,restSec:75},
  ["Pied arrière posé sur le banc, pied avant à bonne distance pour un genou avant proche de 90°.","Descends à la verticale, genou avant aligné avec le pied.","Remonte en poussant sur le talon avant."],
  "Reste proche d'un support au début : exercice exigeant en équilibre."],
["fentes_avant","Fentes avant",["quadriceps","fessiers"],["bodyweight"],"lunge",true,{sets:3,repsMin:10,repsMax:14,restSec:60},
  ["Grand pas en avant, descends jusqu'à ce que les deux genoux soient proches de 90°.","Genou avant aligné avec le pied, buste droit.","Repousse sur le talon avant pour revenir."],
  "Le genou avant ne doit pas dépasser largement la pointe du pied de façon instable."],
["fentes_arriere","Fentes arrière",["quadriceps","fessiers"],["bodyweight"],"lunge",true,{sets:3,repsMin:10,repsMax:14,restSec:60},
  ["Grand pas en arrière, descends le genou arrière vers le sol sans le poser durement.","Buste droit, poids sur la jambe avant.","Repousse sur le talon avant."],
  "Variante souvent plus confortable pour les genoux sensibles que la fente avant."],
["fentes_marchees","Fentes marchées",["quadriceps","fessiers"],["bodyweight"],"lunge",true,{sets:3,repsMin:10,repsMax:16,restSec:75},
  ["Avance en fente, genou avant à ~90°, puis enchaîne le pas suivant.","Garde le buste droit et le gainage actif.","Alterne les jambes à chaque pas."],
  "Prévoir assez d'espace ; ralentis si l'équilibre devient précaire."],
["pont_fessier","Pont fessier",["fessiers","ischios"],["bodyweight"],"hinge",false,{sets:3,repsMin:12,repsMax:20,restSec:45},
  ["Allongé, genoux fléchis, pieds à plat proches du bassin.","Pousse les hanches vers le haut en serrant les fessiers, corps aligné genoux-hanches-épaules.","Redescends contrôlé sans reposer complètement."],
  "Évite de cambrer excessivement le bas du dos en haut du mouvement."],
["pont_fessier_uni","Pont fessier unilatéral",["fessiers","ischios"],["bodyweight"],"hinge",true,{sets:3,repsMin:8,repsMax:12,restSec:45},
  ["Une jambe tendue en l'air, l'autre pied au sol.","Pousse les hanches vers le haut en gardant le bassin de niveau.","Redescends contrôlé."],
  "Si le bassin bascule d'un côté, réduis l'amplitude."],
["planche","Planche (gainage)",["abdos"],["bodyweight"],"core",false,{sets:3,repsMin:20,repsMax:45,restSec:45},
  ["Avant-bras au sol sous les épaules, corps aligné tête-talons.","Serre abdos et fessiers, ne laisse pas le bassin tomber ni monter.","Respire normalement pendant le maintien (durée en secondes)."],
  "Arrête si le bas du dos se creuse : réduis la durée plutôt que de perdre la position."],
["planche_laterale","Planche latérale",["abdos"],["bodyweight"],"core",true,{sets:3,repsMin:15,repsMax:30,restSec:45},
  ["Appui sur un avant-bras, corps aligné de la tête aux pieds.","Hanche décollée du sol, gainage latéral actif.","Maintiens la position (durée en secondes) puis change de côté."],
  "Empile bien les épaules et les hanches pour ne pas tourner le buste."],
["superman","Superman",["dos","fessiers"],["bodyweight"],"core",false,{sets:3,repsMin:10,repsMax:15,restSec:45},
  ["Allongé sur le ventre, bras tendus devant.","Soulève simultanément bras, poitrine et jambes de quelques centimètres.","Redescends contrôlé."],
  "Mouvement d'amplitude modérée : ne cherche pas à monter très haut, privilégie le contrôle."],
["mountain_climbers","Mountain climbers",["abdos","cardio"],["bodyweight"],"core",false,{sets:3,repsMin:20,repsMax:30,restSec:45},
  ["Position de planche haute, mains sous les épaules.","Ramène un genou vers la poitrine puis alterne rapidement.","Garde le bassin stable, sans le faire remonter."],
  "Ralentis si le bas du dos bouge beaucoup : la stabilité du bassin prime sur la vitesse."],
["crunch","Crunch abdominaux",["abdos"],["bodyweight"],"core",false,{sets:3,repsMin:15,repsMax:25,restSec:45},
  ["Allongé, genoux fléchis, mains légèrement derrière la tête sans tirer sur la nuque.","Enroule le buste vers les genoux en expirant.","Redescends contrôlé sans reposer brutalement."],
  "Ne tire pas sur la tête avec les mains ; le mouvement vient des abdominaux."],
["releve_jambes","Relevé de jambes",["abdos"],["bodyweight"],"core",false,{sets:3,repsMin:10,repsMax:15,restSec:45},
  ["Allongé, jambes tendues, bas du dos au contact du sol.","Descends les jambes tant que le bas du dos reste plaqué au sol.","Remonte contrôlé."],
  "Plie les genoux pour réduire le levier si le bas du dos décolle du sol."],
["burpees","Burpees",["cardio","quadriceps","pect"],["bodyweight"],"core",false,{sets:3,repsMin:8,repsMax:15,restSec:60},
  ["Depuis debout, descends en squat, pose les mains, envoie les pieds en planche.","Fais une pompe (optionnelle), ramène les pieds, saute vers le haut.","Enchaîne à un rythme régulier plutôt que maximal d'emblée."],
  "Exercice cardiovasculaire exigeant : ralentis la cadence en cas d'essoufflement excessif."],
["jumping_jacks","Jumping jacks",["cardio"],["bodyweight"],"core",false,{sets:3,repsMin:20,repsMax:40,restSec:30},
  ["Départ pieds joints, bras le long du corps.","Saute en écartant simultanément jambes et bras au-dessus de la tête.","Reviens à la position de départ, enchaîne à rythme régulier."],
  "Bon échauffement cardio ; réduis l'amplitude si les articulations des chevilles/genoux sont sensibles."],
["bird_dog","Bird-dog",["abdos","dos"],["bodyweight"],"core",true,{sets:3,repsMin:8,repsMax:12,restSec:45},
  ["À quatre pattes, dos neutre.","Tends simultanément un bras et la jambe opposée à l'horizontale.","Reviens contrôlé, alterne les côtés."],
  "Garde le bassin stable : évite de le faire tourner pendant l'extension."],
["mollets_pdc","Mollets debout (poids du corps)",["mollets"],["bodyweight"],"calf",false,{sets:3,repsMin:15,repsMax:25,restSec:45},
  ["Debout, pieds à plat, éventuellement en appui sur un support pour l'équilibre.","Monte sur la pointe des pieds le plus haut possible.","Redescends contrôlé sans rebondir."],
  "Mouvement lent et contrôlé plutôt que rebondi, pour bien solliciter le mollet."],
["chaise_murale","Chaise contre le mur",["quadriceps"],["bodyweight"],"squat",false,{sets:3,repsMin:20,repsMax:45,restSec:45},
  ["Dos au mur, descends jusqu'à cuisses proches de l'horizontale, genoux à 90°.","Maintiens la position (durée en secondes), genoux alignés avec les pieds.","Remonte en poussant sur les talons."],
  "Arrête si une douleur au genou apparaît (différente de la fatigue musculaire normale)."],
["pompe_pike","Pompe pike",["epaules","triceps"],["bodyweight"],"push",false,{sets:3,repsMin:6,repsMax:12,restSec:75},
  ["Position en V inversé, mains au sol, hanches hautes.","Descends la tête vers le sol en fléchissant les coudes.","Repousse pour revenir en position haute."],
  "Bonne préparation au développé militaire sans charge ; progresse graduellement en amplitude."],
["tractions","Tractions (pronation)",["dos","biceps"],["bodyweight","pullup_bar"],"pull",false,{sets:3,repsMin:4,repsMax:10,restSec:90},
  ["Suspendu, mains un peu plus larges que les épaules, paumes vers l'avant.","Tire en amenant le menton au-dessus de la barre, coudes vers le bas.","Redescends contrôlé jusqu'à extension complète des bras."],
  "Évite les à-coups (kipping non contrôlé) qui stressent l'épaule ; privilégie un mouvement strict."],
["tractions_suppination","Tractions (supination)",["biceps","dos"],["bodyweight","pullup_bar"],"pull",false,{sets:3,repsMin:4,repsMax:10,restSec:90},
  ["Suspendu, paumes vers soi, mains largeur d'épaules.","Tire en amenant le menton au-dessus de la barre.","Redescends contrôlé jusqu'à extension complète."],
  "Sollicite davantage les biceps ; même prudence que la traction classique sur les à-coups."],
["suspension_barre","Suspension à la barre",["avantbras","dos"],["bodyweight","pullup_bar"],"pull",false,{sets:3,repsMin:20,repsMax:40,restSec:60},
  ["Suspendu à la barre, épaules légèrement engagées (pas totalement relâchées).","Maintiens la position (durée en secondes).","Redescends en douceur."],
  "Bon exercice de renforcement des avant-bras et de décompression du dos, à intensité douce."],
["dc_haltere","Développé couché haltères",["pect","triceps","epaules"],["dumbbells","bench"],"push",false,{sets:3,repsMin:8,repsMax:12,restSec:90},
  ["Allongé sur le banc, haltères au niveau de la poitrine, coudes à ~45°.","Pousse les haltères vers le haut sans les entrechoquer, extension quasi complète.","Redescends contrôlé jusqu'à un étirement confortable de la poitrine."],
  "Garde toujours le contrôle de la charge, surtout en fin de série ; utilise un poids que tu peux reposer en sécurité."],
["dc_incline_haltere","Développé incliné haltères",["pect","epaules","triceps"],["dumbbells","bench"],"push",false,{sets:3,repsMin:8,repsMax:12,restSec:90},
  ["Banc incliné à 30-45°, haltères au niveau du haut de la poitrine.","Pousse vers le haut en gardant les omoplates serrées contre le banc.","Redescends contrôlé."],
  "Une inclinaison trop forte (>45°) sollicite davantage l'épaule que le haut des pectoraux."],
["ecarte_couche","Écarté couché haltères",["pect"],["dumbbells","bench"],"push",false,{sets:3,repsMin:10,repsMax:15,restSec:75},
  ["Allongé, haltères au-dessus de la poitrine, légère flexion des coudes maintenue.","Ouvre les bras en arc de cercle jusqu'à un étirement confortable.","Ramène les haltères en contractant les pectoraux."],
  "Ne descends pas plus bas que ce que l'épaule tolère sans tension excessive à l'avant."],
["rowing_uni_haltere","Rowing haltère unilatéral",["dos","biceps"],["dumbbells","bench"],"pull",true,{sets:3,repsMin:8,repsMax:12,restSec:75},
  ["Un genou et une main en appui sur le banc, dos plat et parallèle au sol.","Tire l'haltère vers la hanche en amenant le coude vers l'arrière.","Redescends contrôlé jusqu'à extension complète du bras."],
  "Garde le dos plat pendant tout le mouvement, sans le tordre pour tirer la charge."],
["rowing_deux_halteres","Rowing buste penché (deux haltères)",["dos","biceps"],["dumbbells"],"pull",false,{sets:3,repsMin:8,repsMax:12,restSec:75},
  ["Buste penché en avant, dos plat, genoux légèrement fléchis, haltères pendants.","Tire les haltères vers les hanches, coudes vers l'arrière.","Redescends contrôlé."],
  "Garde le dos neutre tout du long ; si tu ne peux pas maintenir cet angle, redresse un peu le buste."],
["dev_epaules_haltere","Développé épaules haltères",["epaules","triceps"],["dumbbells"],"push",false,{sets:3,repsMin:8,repsMax:12,restSec:90},
  ["Assis ou debout, haltères au niveau des épaules, paumes vers l'avant.","Pousse vers le haut sans cambrer excessivement le bas du dos.","Redescends contrôlé jusqu'aux épaules."],
  "Garde le gainage actif pour éviter de compenser avec le bas du dos, surtout debout."],
["elevations_laterales","Élévations latérales",["epaules"],["dumbbells"],"push",false,{sets:3,repsMin:12,repsMax:15,restSec:60},
  ["Debout, haltères le long du corps, légère flexion des coudes.","Lève les bras sur les côtés jusqu'à hauteur d'épaule.","Redescends contrôlé sans élan."],
  "Évite de monter au-dessus de la hauteur d'épaule avec une charge lourde : cela stresse l'articulation."],
["elevations_frontales","Élévations frontales",["epaules"],["dumbbells"],"push",false,{sets:3,repsMin:10,repsMax:15,restSec:60},
  ["Debout, haltères devant les cuisses.","Lève un bras (ou les deux) tendu jusqu'à hauteur d'épaule.","Redescends contrôlé."],
  "Ne cambre pas le dos pour gagner de l'amplitude : garde le buste stable."],
["oiseau_haltere","Oiseau (élévation arrière)",["epaules","dos"],["dumbbells"],"pull",false,{sets:3,repsMin:12,repsMax:15,restSec:60},
  ["Buste penché en avant, dos plat, haltères pendants devant.","Écarte les bras sur les côtés en serrant les omoplates.","Redescends contrôlé."],
  "Utilise une charge légère : c'est un mouvement d'isolation qui tolère peu de triche."],
["curl_biceps","Curl biceps haltères",["biceps"],["dumbbells"],"pull",false,{sets:3,repsMin:8,repsMax:12,restSec:60},
  ["Debout, haltères le long du corps, coudes proches du buste.","Fléchis les coudes pour monter les haltères, sans balancer le buste.","Redescends contrôlé jusqu'à extension complète."],
  "Évite l'élan du buste pour « tricher » la fin de série : réduis la charge plutôt."],
["curl_marteau","Curl marteau",["biceps","avantbras"],["dumbbells"],"pull",false,{sets:3,repsMin:8,repsMax:12,restSec:60},
  ["Debout, haltères en prise neutre (paumes face à face).","Fléchis les coudes en gardant les poignets neutres.","Redescends contrôlé."],
  "Sollicite aussi l'avant-bras ; garde un tempo contrôlé pour éviter les à-coups au poignet."],
["extension_triceps_nuque","Extension triceps nuque",["triceps"],["dumbbells"],"push",false,{sets:3,repsMin:8,repsMax:12,restSec:75},
  ["Assis ou debout, un haltère tenu à deux mains au-dessus de la tête.","Descends l'haltère derrière la tête en fléchissant les coudes, coudes fixes.","Remonte en étendant les bras sans les verrouiller brutalement."],
  "Garde les coudes proches de la tête ; ne descends pas si tu perds le contrôle de la charge."],
["kickback_triceps","Kickback triceps",["triceps"],["dumbbells","bench"],"push",true,{sets:3,repsMin:10,repsMax:15,restSec:60},
  ["Buste penché, un genou et une main en appui sur le banc, bras haut parallèle au sol.","Étends l'avant-bras vers l'arrière, coude fixe.","Reviens contrôlé."],
  "Mouvement d'isolation léger : privilégie la maîtrise du geste à la charge."],
["squat_gobelet","Squat gobelet (goblet squat)",["quadriceps","fessiers"],["dumbbells"],"squat",false,{sets:3,repsMin:10,repsMax:15,restSec:90},
  ["Tiens un haltère à deux mains contre la poitrine.","Descends hanches en arrière et vers le bas, dos neutre, coudes entre les genoux.","Remonte en poussant le sol."],
  "Excellent exercice d'apprentissage du squat : privilégie la profondeur atteignable sans arrondir le dos."],
["fentes_halteres","Fentes haltères",["quadriceps","fessiers"],["dumbbells"],"lunge",true,{sets:3,repsMin:8,repsMax:12,restSec:75},
  ["Haltères le long du corps, grand pas en avant ou en arrière.","Descends jusqu'à un angle proche de 90° au genou avant.","Repousse sur le talon avant pour revenir."],
  "Commence avec une charge légère pour valider l'équilibre avant d'augmenter le poids."],
["rdl_halteres","Soulevé de terre jambes tendues (haltères)",["ischios","fessiers"],["dumbbells"],"hinge",false,{sets:3,repsMin:8,repsMax:12,restSec:90},
  ["Haltères devant les cuisses, genoux légèrement fléchis, dos neutre.","Bascule le bassin en arrière en laissant descendre les haltères le long des jambes.","Remonte en poussant les hanches vers l'avant, sans arrondir le dos."],
  "Le dos doit rester neutre du début à la fin ; arrête la descente dès que tu sens le dos s'arrondir."],
["rdl_uni_haltere","Soulevé de terre roumain unilatéral",["ischios","fessiers"],["dumbbells"],"hinge",true,{sets:3,repsMin:6,repsMax:10,restSec:75},
  ["Sur une jambe, haltère du côté opposé, dos neutre.","Bascule le buste vers l'avant en levant la jambe libre vers l'arrière.","Reviens contrôlé en gardant le bassin de niveau."],
  "Exercice d'équilibre exigeant : commence à charge très légère voire à vide."],
["mollets_halteres","Mollets debout (haltères)",["mollets"],["dumbbells"],"calf",false,{sets:3,repsMin:15,repsMax:20,restSec:45},
  ["Haltères le long du corps, pieds à plat.","Monte sur la pointe des pieds le plus haut possible.","Redescends contrôlé sans rebondir."],
  "Mouvement lent, amplitude complète, sans rebond pour maximiser le travail du mollet."],
["shrugs_halteres","Shrugs (trapèzes) haltères",["dos"],["dumbbells"],"pull",false,{sets:3,repsMin:12,repsMax:15,restSec:60},
  ["Debout, haltères le long du corps.","Monte les épaules vers les oreilles sans rouler les épaules.","Redescends contrôlé."],
  "Évite de rouler les épaules en cercle avec une charge lourde : monte-descends verticalement."],
["thruster_haltere","Thruster haltères",["quadriceps","epaules","fessiers"],["dumbbells"],"squat",false,{sets:3,repsMin:8,repsMax:12,restSec:90},
  ["Haltères au niveau des épaules, descends en squat complet.","Remonte en poussant sur les jambes et enchaîne un développé épaules.","Redescends les haltères aux épaules avant la répétition suivante."],
  "Exercice combiné exigeant en cardio : commence avec une charge modérée pour garder la forme."],
["squat_barre","Squat barre (back squat)",["quadriceps","fessiers"],["barbell"],"squat",false,{sets:4,repsMin:5,repsMax:10,restSec:120},
  ["Barre posée sur le haut du dos (trapèzes), pieds largeur d'épaules.","Descends hanches en arrière et vers le bas, dos neutre, genoux dans l'axe des pieds.","Remonte en poussant le sol, sans perdre l'alignement du dos."],
  "Utilise un cadre de sécurité ou des supports réglés à hauteur de squat si tu t'entraînes seul avec une charge proche du maximum."],
["dc_barre","Développé couché barre",["pect","triceps","epaules"],["barbell","bench"],"push",false,{sets:4,repsMin:5,repsMax:10,restSec:120},
  ["Allongé, prise un peu plus large que les épaules, barre au niveau de la poitrine.","Descends la barre contrôlée jusqu'à toucher légèrement la poitrine.","Pousse vers le haut en expirant, sans rebondir sur la poitrine."],
  "Entraîne-toi avec un partenaire ou des butées de sécurité pour les charges proches du maximum ; ne bloque jamais les coudes brutalement."],
["deadlift_barre","Soulevé de terre (deadlift)",["ischios","fessiers","dos"],["barbell"],"hinge",false,{sets:4,repsMin:4,repsMax:8,restSec:150},
  ["Barre proche des tibias, dos neutre, poitrine haute, prise juste à l'extérieur des jambes.","Pousse le sol avec les jambes en gardant la barre proche du corps jusqu'à l'extension complète des hanches.","Redescends en inversant le mouvement, dos toujours neutre."],
  "Le soulevé de terre est technique : commence avec une charge légère pour ancrer la position de dos neutre avant de charger davantage."],
["militaire_barre","Développé militaire barre",["epaules","triceps"],["barbell"],"push",false,{sets:3,repsMin:6,repsMax:10,restSec:120},
  ["Debout, barre au niveau des clavicules, prise un peu plus large que les épaules.","Pousse la barre au-dessus de la tête en gainant fort, sans cambrer excessivement.","Redescends contrôlé jusqu'aux clavicules."],
  "Garde les abdos et fessiers contractés pour protéger le bas du dos pendant la poussée."],
["rowing_barre","Rowing barre buste penché",["dos","biceps"],["barbell"],"pull",false,{sets:3,repsMin:6,repsMax:10,restSec:90},
  ["Buste penché à ~45°, dos neutre, barre pendante bras tendus.","Tire la barre vers le bas du buste, coudes vers l'arrière.","Redescends contrôlé sans perdre l'angle du dos."],
  "Si tu ne peux pas garder le dos neutre à cet angle, redresse légèrement le buste ou réduis la charge."],
["hip_thrust_barre","Hip thrust barre",["fessiers","ischios"],["barbell","bench"],"hinge",false,{sets:3,repsMin:8,repsMax:12,restSec:90},
  ["Haut du dos calé sur le banc, barre sur les hanches (protège avec une serviette/pad).","Pousse les hanches vers le haut jusqu'à extension complète, menton rentré.","Redescends contrôlé sans reposer brutalement."],
  "Positionne la barre confortablement sur les hanches avant de charger lourd pour éviter l'inconfort."],
["swing_kb","Swing kettlebell",["fessiers","ischios","cardio"],["kettlebell"],"hinge",false,{sets:3,repsMin:12,repsMax:20,restSec:75},
  ["Pieds largeur d'épaules, kettlebell tenue à deux mains devant.","Bascule le bassin en arrière (hinge, pas un squat) puis pousse les hanches vers l'avant pour projeter la kettlebell à hauteur de poitrine.","Laisse la kettlebell redescendre entre les jambes en contrôlant le mouvement."],
  "Le mouvement part des hanches, pas des bras ni du bas du dos : arrête si tu sens le dos travailler plus que les hanches."],
["goblet_squat_kb","Goblet squat kettlebell",["quadriceps","fessiers"],["kettlebell"],"squat",false,{sets:3,repsMin:10,repsMax:15,restSec:90},
  ["Kettlebell tenue contre la poitrine par les cornes.","Descends hanches en arrière et vers le bas, dos neutre.","Remonte en poussant le sol."],
  "Même repère de sécurité que le goblet squat haltère : privilégie la profondeur atteignable sans arrondir le dos."],
["deadlift_kb","Soulevé de terre kettlebell",["ischios","fessiers"],["kettlebell"],"hinge",false,{sets:3,repsMin:8,repsMax:12,restSec:90},
  ["Kettlebell entre les pieds, dos neutre, genoux légèrement fléchis.","Pousse le sol avec les jambes en gardant la kettlebell proche du corps.","Redescends contrôlé, dos toujours neutre."],
  "Charge légère au départ pour ancrer la technique de hinge avant d'augmenter le poids."],
["rowing_uni_kb","Rowing kettlebell unilatéral",["dos","biceps"],["kettlebell","bench"],"pull",true,{sets:3,repsMin:8,repsMax:12,restSec:75},
  ["Un genou et une main en appui sur le banc, dos plat.","Tire la kettlebell vers la hanche, coude vers l'arrière.","Redescends contrôlé."],
  "Garde le dos plat pendant tout le mouvement."],
["kb_overhead_press","Développé kettlebell",["epaules","triceps"],["kettlebell"],"push",true,{sets:3,repsMin:6,repsMax:10,restSec:90},
  ["Kettlebell en position de rack contre l'avant-bras/épaule.","Pousse vers le haut jusqu'à extension complète du bras.","Redescends contrôlé jusqu'au rack."],
  "Garde le gainage actif ; travaille un bras à la fois pour bien contrôler la trajectoire."],
["tirage_elastique","Tirage élastique horizontal",["dos","biceps"],["bands"],"pull",false,{sets:3,repsMin:12,repsMax:20,restSec:60},
  ["Élastique fixé à hauteur de poitrine ou tenu tendu devant soi, bras tendus.","Tire les mains vers les côtes en serrant les omoplates.","Reviens contrôlé jusqu'à extension complète."],
  "Choisis une résistance qui permet de garder le buste immobile pendant toute la série."],
["ecarte_elastique","Écarté élastique (pull-apart)",["epaules","dos"],["bands"],"pull",false,{sets:3,repsMin:12,repsMax:20,restSec:45},
  ["Élastique tenu à deux mains devant soi, bras tendus.","Écarte les mains en ouvrant les bras jusqu'à ce que l'élastique touche la poitrine.","Reviens contrôlé."],
  "Excellent exercice de santé d'épaule ; privilégie un tempo lent et contrôlé."],
["squat_elastique","Squat élastique",["quadriceps","fessiers"],["bands"],"squat",false,{sets:3,repsMin:12,repsMax:20,restSec:60},
  ["Élastique sous les pieds, tenu au niveau des épaules ou fixé sous les pieds selon le modèle.","Descends en squat, dos neutre, genoux dans l'axe des pieds.","Remonte en poussant le sol contre la résistance."],
  "Garde la même vigilance sur l'alignement des genoux que pour un squat classique."],
["extension_triceps_elastique","Extension triceps élastique",["triceps"],["bands"],"push",false,{sets:3,repsMin:12,repsMax:20,restSec:45},
  ["Élastique fixé en hauteur, coude fléchi près de la tête.","Étends l'avant-bras vers le bas, coude fixe.","Reviens contrôlé."],
  "Garde le coude immobile tout du long pour bien isoler le triceps."],
["curl_biceps_elastique","Curl biceps élastique",["biceps"],["bands"],"pull",false,{sets:3,repsMin:12,repsMax:20,restSec:45},
  ["Élastique sous les pieds, coudes proches du buste.","Fléchis les coudes pour amener les mains vers les épaules.","Reviens contrôlé."],
  "Évite de balancer le buste pour compenser en fin de série."],
["band_walk","Marche latérale élastique",["fessiers"],["bands"],"squat",true,{sets:3,repsMin:10,repsMax:15,restSec:45},
  ["Élastique placé au-dessus des genoux ou des chevilles, légère flexion des genoux.","Fais des pas latéraux en gardant la tension dans l'élastique.","Garde les hanches de niveau, sans te pencher."],
  "Reste en position mi-squat basse tout du long pour maximiser le travail des fessiers moyens."],

// ---- ajouts v1.3 ----
// poids du corps
["pompes_diamant","Pompes serrées (diamant)",["triceps","pect","epaules"],["bodyweight"],"push",false,{sets:3,repsMin:6,repsMax:12,restSec:75},
  ["Mains rapprochées sous la poitrine, index et pouces formant un losange.","Descends en gardant les coudes près du corps, corps aligné.","Pousse en expirant jusqu'à l'extension des bras."],
  "Plus exigeant pour les poignets et les coudes : écarte un peu les mains si tu ressens une gêne articulaire."],
["pompes_larges","Pompes prise large",["pect","epaules","triceps"],["bodyweight"],"push",false,{sets:3,repsMin:8,repsMax:15,restSec:75},
  ["Mains nettement plus larges que les épaules, corps aligné.","Descends la poitrine vers le sol en contrôlant.","Pousse en expirant sans laisser le bassin s'affaisser."],
  "N'écarte pas les mains au point de sentir une tension à l'avant de l'épaule."],
["fentes_laterales","Fentes latérales",["quadriceps","fessiers"],["bodyweight"],"lunge",true,{sets:3,repsMin:8,repsMax:12,restSec:60},
  ["Grand pas sur le côté, pied orienté vers l'avant.","Fléchis la jambe d'appui en poussant les hanches en arrière, l'autre jambe reste tendue.","Repousse sur le pied fléchi pour revenir au centre."],
  "Garde le genou fléchi dans l'axe du pied ; réduis l'amplitude si l'intérieur de la cuisse tire trop."],
["squat_saute","Squat sauté",["quadriceps","fessiers","cardio"],["bodyweight"],"squat",false,{sets:3,repsMin:8,repsMax:12,restSec:75},
  ["Descends en squat, dos neutre.","Pousse fort dans le sol pour sauter verticalement.","Réceptionne-toi en douceur sur l'avant des pieds, genoux fléchis, et enchaîne."],
  "Exercice à impact : maîtrise d'abord le squat classique, et arrête si les genoux ou les chevilles sont douloureux."],
["gainage_creux","Gainage creux (hollow hold)",["abdos"],["bodyweight"],"core",false,{sets:3,repsMin:15,repsMax:40,restSec:45},
  ["Allongé sur le dos, bas du dos plaqué au sol.","Décolle épaules et jambes tendues de quelques centimètres, bras le long du corps ou tendus derrière la tête.","Maintiens la position (durée en secondes) en respirant calmement."],
  "Si le bas du dos décolle, plie les genoux ou remonte les jambes plus haut."],
["dead_bug","Dead bug",["abdos"],["bodyweight"],"core",true,{sets:3,repsMin:8,repsMax:12,restSec:45},
  ["Allongé sur le dos, bras tendus vers le plafond, hanches et genoux à 90°.","Tends lentement un bras vers l'arrière et la jambe opposée vers l'avant.","Reviens au centre et alterne, bas du dos plaqué au sol."],
  "Va lentement : si le bas du dos se creuse, réduis l'amplitude du mouvement."],
["mollets_uni_pdc","Mollets unilatéral (poids du corps)",["mollets"],["bodyweight"],"calf",true,{sets:3,repsMin:10,repsMax:20,restSec:45},
  ["Debout sur une jambe, une main en appui pour l'équilibre.","Monte sur la pointe du pied le plus haut possible.","Redescends lentement, idéalement talon sous le niveau de la marche si tu es sur une marche."],
  "Mouvement contrôlé, sans rebond en bas de l'amplitude."],
// barre de traction
["releve_genoux_suspendu","Relevé de genoux suspendu",["abdos"],["bodyweight","pullup_bar"],"core",false,{sets:3,repsMin:8,repsMax:15,restSec:60},
  ["Suspendu à la barre, épaules engagées.","Remonte les genoux vers la poitrine en enroulant légèrement le bassin.","Redescends lentement sans te balancer."],
  "Évite le balancier : si tu oscilles, marque un temps d'arrêt en bas avant chaque répétition."],
// haltères — pectoraux
["floor_press_haltere","Développé au sol haltères",["pect","triceps"],["dumbbells"],"push",false,{sets:3,repsMin:8,repsMax:12,restSec:90},
  ["Allongé au sol, genoux fléchis, haltères au-dessus de la poitrine.","Descends jusqu'à ce que l'arrière des bras touche doucement le sol.","Pousse les haltères vers le haut en expirant."],
  "Pratique sans banc ; pose les coudes en douceur au sol, sans rebond."],
["ecarte_sol","Écarté au sol haltères",["pect"],["dumbbells"],"push",false,{sets:3,repsMin:10,repsMax:15,restSec:60},
  ["Allongé au sol, haltères au-dessus de la poitrine, coudes légèrement fléchis.","Ouvre les bras en arc de cercle jusqu'à effleurer le sol avec les bras.","Ramène les haltères au-dessus de la poitrine en serrant les pectoraux."],
  "Utilise une charge légère ; le sol limite l'amplitude et protège l'épaule."],
["squeeze_press","Développé serré haltères (squeeze press)",["pect","triceps"],["dumbbells","bench"],"push",false,{sets:3,repsMin:10,repsMax:12,restSec:75},
  ["Allongé sur le banc, haltères collés l'un contre l'autre au-dessus de la poitrine.","Descends-les ensemble jusqu'à la poitrine en les pressant l'un contre l'autre.","Pousse vers le haut en maintenant la pression entre les haltères."],
  "Charge modérée : la pression constante entre les haltères suffit à solliciter fortement les pectoraux."],
["ecarte_incline","Écarté incliné haltères",["pect","epaules"],["dumbbells","bench"],"push",false,{sets:3,repsMin:10,repsMax:15,restSec:60},
  ["Banc incliné à 30-45°, haltères au-dessus du haut de la poitrine.","Ouvre les bras en arc de cercle, coudes légèrement fléchis.","Ramène les haltères en contractant le haut des pectoraux."],
  "Nécessite un banc réglable ; ne descends pas au-delà d'un étirement confortable de l'épaule."],
["pullover_haltere","Pull-over haltère",["pect","dos"],["dumbbells","bench"],"pull",false,{sets:3,repsMin:10,repsMax:12,restSec:60},
  ["Allongé sur le banc, un haltère tenu à deux mains au-dessus de la poitrine.","Descends l'haltère derrière la tête en arc de cercle, coudes légèrement fléchis.","Ramène-le au-dessus de la poitrine sans cambrer le dos."],
  "Garde une charge légère et arrête la descente avant que l'épaule ou le bas du dos ne compensent."],
// haltères — autres
["arnold_press","Développé Arnold",["epaules","triceps"],["dumbbells"],"push",false,{sets:3,repsMin:8,repsMax:12,restSec:75},
  ["Assis, haltères devant le visage, paumes vers toi.","Pousse vers le haut en tournant les paumes vers l'avant.","Redescends en inversant la rotation."],
  "Mouvement de rotation : charge légère à modérée, sans cambrer le bas du dos."],
["curl_concentre","Curl concentré",["biceps"],["dumbbells","bench"],"pull",true,{sets:3,repsMin:10,repsMax:12,restSec:45},
  ["Assis sur le banc, coude calé contre l'intérieur de la cuisse.","Monte l'haltère vers l'épaule sans bouger le coude.","Redescends lentement jusqu'à l'extension."],
  "Isolation stricte : réduis la charge plutôt que de t'aider du buste."],
["curl_incline","Curl incliné haltères",["biceps"],["dumbbells","bench"],"pull",false,{sets:3,repsMin:8,repsMax:12,restSec:60},
  ["Assis sur un banc incliné, bras pendants, paumes vers l'avant.","Fléchis les coudes sans les avancer.","Redescends lentement jusqu'à l'extension complète."],
  "L'étirement du biceps est important en bas du mouvement : commence plus léger qu'au curl debout."],
["extension_triceps_allonge","Extension triceps allongé (haltères)",["triceps"],["dumbbells","bench"],"push",false,{sets:3,repsMin:8,repsMax:12,restSec:60},
  ["Allongé sur le banc, haltères tendus au-dessus des épaules, paumes face à face.","Fléchis les coudes pour descendre les haltères de chaque côté de la tête.","Tends les bras en gardant les coudes orientés vers le plafond."],
  "Contrôle la descente pour ne jamais approcher les haltères du visage de façon brusque."],
["step_up","Montées sur banc (step-up)",["quadriceps","fessiers"],["dumbbells","bench"],"lunge",true,{sets:3,repsMin:8,repsMax:12,restSec:75},
  ["Haltères le long du corps, pied entier posé sur le banc.","Monte en poussant sur le talon de la jambe posée, sans t'aider de la jambe arrière.","Redescends lentement et contrôlé."],
  "Vérifie que le banc est stable ; commence sans charge pour valider l'équilibre."],
["squat_sumo_haltere","Squat sumo haltère",["quadriceps","fessiers"],["dumbbells"],"squat",false,{sets:3,repsMin:10,repsMax:15,restSec:75},
  ["Pieds plus larges que les épaules, pointes ouvertes, un haltère tenu à deux mains entre les jambes.","Descends en gardant le buste droit et les genoux dans l'axe des pieds.","Remonte en poussant le sol."],
  "Les genoux doivent suivre l'ouverture des pieds, sans rentrer vers l'intérieur."],
["hip_thrust_haltere","Hip thrust haltère",["fessiers","ischios"],["dumbbells","bench"],"hinge",false,{sets:3,repsMin:10,repsMax:15,restSec:75},
  ["Haut du dos calé sur le banc, haltère posé sur les hanches et tenu à deux mains.","Pousse les hanches vers le haut jusqu'à l'alignement épaules-hanches-genoux.","Redescends contrôlé."],
  "Menton rentré et côtes basses en haut du mouvement, pour ne pas cambrer le bas du dos."],
["renegade_row","Rowing renegade",["dos","abdos"],["dumbbells"],"pull",true,{sets:3,repsMin:6,repsMax:10,restSec:75},
  ["En planche haute, mains sur les haltères, pieds écartés pour la stabilité.","Tire un haltère vers la hanche sans faire pivoter le bassin.","Repose-le et alterne."],
  "Utilise des haltères stables (à faces plates) et une charge légère au début."],
["marche_fermier","Marche du fermier",["avantbras","dos","cardio"],["dumbbells"],"core",false,{sets:3,repsMin:20,repsMax:40,restSec:75},
  ["Un haltère lourd dans chaque main, bras le long du corps.","Marche à petits pas, buste droit, épaules basses.","Continue pendant la durée prévue (en secondes), puis repose les haltères en fléchissant les jambes."],
  "Ramasse et repose les haltères dos neutre, comme un soulevé de terre."],
["curl_poignets","Curl poignets haltère",["avantbras"],["dumbbells","bench"],"pull",false,{sets:3,repsMin:12,repsMax:20,restSec:45},
  ["Assis, avant-bras posés sur les cuisses ou le banc, poignets dans le vide, paumes vers le haut.","Enroule les poignets vers le haut.","Redescends lentement."],
  "Charge légère et amplitude contrôlée : les poignets tolèrent mal les à-coups."],
// barre
["curl_barre","Curl barre",["biceps"],["barbell"],"pull",false,{sets:3,repsMin:8,repsMax:12,restSec:60},
  ["Debout, barre tenue en supination, mains largeur d'épaules.","Monte la barre en gardant les coudes près du buste.","Redescends lentement jusqu'à l'extension."],
  "Évite de balancer le buste pour monter la charge."],
["rdl_barre","Soulevé de terre roumain barre",["ischios","fessiers"],["barbell"],"hinge",false,{sets:3,repsMin:6,repsMax:10,restSec:120},
  ["Debout, barre en main devant les cuisses, genoux légèrement fléchis.","Bascule le bassin en arrière, barre le long des cuisses, dos neutre.","Remonte en poussant les hanches vers l'avant."],
  "Arrête la descente dès que le dos commence à s'arrondir ; la barre reste au contact des jambes."],
["dc_incline_barre","Développé incliné barre",["pect","epaules","triceps"],["barbell","bench"],"push",false,{sets:3,repsMin:6,repsMax:10,restSec:120},
  ["Banc incliné à 30-45°, barre au-dessus du haut de la poitrine.","Descends la barre contrôlée vers le haut de la poitrine.","Pousse vers le haut en gardant les omoplates serrées."],
  "Nécessite un banc réglable ; utilise des butées ou un partenaire pour les charges lourdes."],
["dc_serre_barre","Développé couché prise serrée",["triceps","pect"],["barbell","bench"],"push",false,{sets:3,repsMin:6,repsMax:10,restSec:120},
  ["Allongé, mains à largeur d'épaules sur la barre.","Descends la barre vers le bas de la poitrine, coudes près du corps.","Pousse en expirant jusqu'à l'extension."],
  "Ne serre pas les mains plus que la largeur des épaules : une prise trop étroite charge les poignets."],
["barre_front","Barre au front",["triceps"],["barbell","bench"],"push",false,{sets:3,repsMin:8,repsMax:12,restSec:75},
  ["Allongé, barre tendue au-dessus des épaules.","Fléchis les coudes pour descendre la barre vers le front, coudes fixes.","Tends les bras sans verrouiller brutalement."],
  "Charge modérée et descente lente : la barre passe près du visage."],
// kettlebell
["kb_sumo_deadlift","Soulevé de terre sumo kettlebell",["fessiers","quadriceps","ischios"],["kettlebell"],"hinge",false,{sets:3,repsMin:10,repsMax:15,restSec:75},
  ["Pieds larges, pointes ouvertes, kettlebell entre les pieds.","Descends en gardant le dos neutre et saisis la poignée bras tendus.","Remonte en poussant le sol, genoux dans l'axe des pieds."],
  "Dos neutre du début à la fin ; si tu dois arrondir le dos pour attraper la kettlebell, surélève-la."],
["kb_fermier","Marche du fermier kettlebell",["avantbras","dos","cardio"],["kettlebell"],"core",false,{sets:3,repsMin:20,repsMax:40,restSec:75},
  ["Une kettlebell dans chaque main (ou une seule, côté alterné).","Marche à petits pas, buste droit, épaules basses.","Continue pendant la durée prévue (en secondes)."],
  "Avec une seule kettlebell, résiste à l'inclinaison du buste : c'est tout l'intérêt du gainage."],
// élastiques
["face_pull_elastique","Face pull élastique",["epaules","dos"],["bands"],"pull",false,{sets:3,repsMin:12,repsMax:20,restSec:45},
  ["Élastique fixé à hauteur de visage, tenu à deux mains.","Tire vers le visage en écartant les mains, coudes hauts.","Reviens lentement."],
  "Excellent pour l'arrière des épaules ; résistance légère et mouvement contrôlé."],
["dev_epaules_elastique","Développé épaules élastique",["epaules","triceps"],["bands"],"push",false,{sets:3,repsMin:10,repsMax:15,restSec:60},
  ["Élastique sous les pieds, mains à hauteur d'épaules.","Pousse vers le haut jusqu'à l'extension des bras.","Redescends contrôlé."],
  "Gainage actif pour ne pas cambrer le bas du dos pendant la poussée."],
["ecarte_elastique_pect","Écarté pectoraux élastique",["pect"],["bands"],"push",false,{sets:3,repsMin:12,repsMax:20,restSec:45},
  ["Élastique fixé derrière toi à hauteur de poitrine, bras ouverts, coudes légèrement fléchis.","Ramène les mains devant la poitrine en arc de cercle.","Reviens lentement en gardant la tension."],
  "Ne laisse pas l'élastique tirer les bras trop loin en arrière."],
["pont_fessier_elastique","Pont fessier élastique",["fessiers"],["bands"],"hinge",false,{sets:3,repsMin:15,repsMax:20,restSec:45},
  ["Élastique au-dessus des genoux, allongé, pieds à plat.","Monte les hanches en poussant les genoux vers l'extérieur contre l'élastique.","Redescends contrôlé."],
  "Garde les genoux alignés avec les pieds, sans les laisser rentrer."],
];

const EXOS = EXO_RAW.map(([id,n,muscles,equip,pattern,uni,def,cues,safety])=>({
  id,n,muscles,equip,pattern,uni,
  sets:def.sets,repsMin:def.repsMin,repsMax:def.repsMax,restSec:def.restSec,
  cues,safety
}));
const EXO_MAP = {}; EXOS.forEach(e=>EXO_MAP[e.id]=e);
// exercices mesurés en secondes plutôt qu'en répétitions (planche, chaise, marche du fermier…)
function isTimed(def){ return def.cues.some(c=>/en secondes/.test(c)); }
